services:
    # Run the node application
    app:
        restart: unless-stopped
        environment: 
            - NODE_ENV=production
        build:
              context: ./.deploy
        env_file:
          - .env
        healthcheck:
              test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}"]
              interval: 10s
              timeout: 5s
              retries: 3

    # Run the caddy server        
    caddy:
        image: caddy/caddy:2.2.1-alpine
        container_name: caddy-service
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        env_file:
          - .env
        volumes:            
        - ./.deploy/Caddyfile:/etc/caddy/Caddyfile
        - ./site:/srv
        - caddy_data:/data
        - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: 
