name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd node-zero-downtime-deployment
            echo $PWD
            git fetch origin main:main
            ./docker_update.sh app
